[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerTarget = "prod"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[[envVars]]
name = "NODE_ENV"
value = "production"
